apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story-deployment
          image: rbverissimo/story-kub-data # pushed to dockerhub image
          env: 
            #- name: STORY_FOLDER  configuration for using env into the deployment
            #  value: 'story'
            - name: STORY_FOLDER
              valueFrom:
                configMapKeyRef:
                  name: data-store-env
                  key: folder 
          volumeMounts:
            - mountPath: /app/story # workdir + path inside the container
              name: story-volume
      volumes:
        - name: story-volume
          #emptyDir: {}
          #hostPath: #a bit like a bind mount on containers
          #  path: /data
          #  type: DirectoryOrCreate
          persistentVolumeClaim:
            claimName: host-pvc

